PROJECT := {{ project_name }}
BUILD_DIR ?= build
ELF := $(BUILD_DIR)/$(PROJECT).elf

CMAKE ?= cmake
GENERATOR ?= Ninja
OPENOCD ?= openocd
OPENOCD_CMDS := {{ openocd_commands }}

.PHONY: all build clean flash

all: build

$(BUILD_DIR)/CMakeCache.txt:
	$(CMAKE) -S . -B $(BUILD_DIR) -G $(GENERATOR)

build: $(BUILD_DIR)/CMakeCache.txt
	$(CMAKE) --build $(BUILD_DIR)

clean:
	$(CMAKE) --build $(BUILD_DIR) --target clean

flash: build
	$(OPENOCD) -f {{ openocd_interface_cfg }} -f {{ openocd_target_cfg }} -c "$(OPENOCD_CMDS)"
